version: "3.5"

services:

  backend:
    container_name: web_app_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"

  redis:
    image: "redis:alpine"

  frontend:
    container_name: web_app_frontend
    depends_on:
      - "backend"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_WEB_API=0.0.0.0:5000
